//----------------------------------------------------------------------------------------------------------------------
//
// This file is part of fabFORCE DBDesigner4.
// Copyright (C) 2002 Michael G. Zinner, www.fabFORCE.net
//
// DBDesigner4 is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// DBDesigner4 is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with DBDesigner4; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
//----------------------------------------------------------------------------------------------------------------------
//
// Unit DBDesigner4.inc
// --------------------
// Version 1.1, 01.08.2003, Mike
// Description
//   Contains various defines
//
// Changes:
//   Version 1.1, 01.08.2003, Mike
//     added USE_IXMLDBMODELType
//   Version 1.0, 13.06.2003, Mike
//     initial version, Mike
//
//----------------------------------------------------------------------------------------------------------------------

//Use this define to include SynEdit for SQL Memos
{$DEFINE USE_SYNEDIT}
{$DEFINE USE_IXMLDBMODELType}
{.$DEFINE USE_QTheming}