//----------------------------------------------------------------------------------------------------------------------
//
// This file is part of the SimpleWebFront-DBDesigner4-Plugin.
// Copyright (C) 2003 Bayer Ulrich
//
// The SimpleWebFront-DBDesigner4-Plugin is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// SimpleWebFront-DBDesigner4-Plugin is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with DBDesigner4; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
//----------------------------------------------------------------------------------------------------------------------

unit StringConstants;

interface
resourcestring
  ArgumentError = 'This programm expects a DBDesigner4-model-file as argument! '  +
                  'Probably you didn''t start this program from within the DBDesigner!';
  NoLayoutError = 'Could not find any layout! Please check your data-Directory!';
  OutputSuccessful = 'Files were successfully created!';
  OutputDirDoesntExist = 'The output-directory doesn''t exist. Should it be created?';
  SaveSuccessful = 'Successfully saved to ';
  Group_TablesOverview = 'The following tables are in region';
  Group_ViewsBeCreated = 'Should views corresponding to these tables be created and assigned to this group?';


  //EditorView
  CheckErrorString_CharNotAllowed = 'A viewname must not contain any of the following chars: \ / : * ? " < > |';
  CheckErrorString_NoViewname = 'The viewname must not be empty!';
  CheckErrorString_NoTable = 'You have to select a table for the view!';
  
  //EditorGroup
  NoGroupEntered = 'Please enter a Name for the group!';
  Group_CharNotAllowed = 'A groupname must not contain any of the following chars: \ / : * ? " < > |';
  NoLineEntered  = 'Please enter a line number!';
  NoColumnEntered = 'Please enter a column number!';
  LineColumnCombinationNotUnique = 'The place specified by the line- and column-number is already occupied!';

  //Weboutput
  GeneratedFileHeader = '<!-- This file was generated by the SimpleWebFront-DBDesigner4-Plugin. See http://www.fabforce.net -->';
  TemplateFileError = 'Error: Specified Templatefile doesn''t exist. Could not successfully finish the creation of the webpages!';
implementation

end.
 